// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.factory('Factory', function($resource) {
    return $resource("api/students/:id", {
      id: '@id'
    }, {
      query: {
        method: 'GET',
        isArray: true
      },
      get: {
        params: {
          id: "@id"
        }
      }
    });
  });

}).call(this);

//# sourceMappingURL=Factory.js.map