// <auto-generated />
namespace SiteAngular.Database.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class StudentTableAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentTableAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201407261347592_StudentTable-Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
