// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.run([
    '$rootScope', '$state', '$stateParams', function($rootScope, $state, $stateParams) {
      return $rootScope.$on("$stateChangeSuccess", function(event, toState, toParams, fromState, fromParams) {
        console.log("route changed");
      });
    }
  ]);

  SiteAngular.Student.config(function($stateProvider, $urlRouterProvider) {
    return $stateProvider.state('Start', {
      url: '',
      templateUrl: '/Student/List',
      controller: 'List'
    }).state('List', {
      url: '/',
      templateUrl: '/Student/List',
      controller: 'List'
    }).state('Create', {
      url: '/student/create',
      templateUrl: '/Student/Create',
      controller: 'Create'
    }).state('Edit', {
      url: '/students/edit/:id',
      templateUrl: '/Student/Edit',
      controller: 'Edit'
    });
  });

}).call(this);

//# sourceMappingURL=routes.js.map