// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.config(function($stateProvider, $urlRouterProvider) {
    return $stateProvider.state('Create', {
      url: '/student/create',
      templateUrl: '/Student/Create'
    }).state('List', {
      url: '/',
      templateUrl: '/Student/List'
    }).state('Edit', {
      url: '/students/edit/:id',
      templateUrl: '/Student/Edit'
    });
  });

}).call(this);

//# sourceMappingURL=routes.js.map