// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.controller('Create', [
    '$scope', '$state', 'Factory', function($scope, $state, Factory) {
      return $scope.Create = function(student) {
        return Factory.save(student).$promise.then(function(result) {
          console.log(result);
          return $state.go('List');
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=Create.js.map