// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.controller('Create', [
    '$scope', '$state', 'Factory', function($scope, $state, Factory) {
      return $scope.Create = function(student) {
        if (student === void 0) {
          toastr.error("Please fill the required input fields");
          return;
        }
        return Factory.save(student).$promise.then(function(result) {
          console.log(result);
          return $state.go('List');
        }, function(error) {
          console.log(error);
          return toastr.error(error.data);
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=Create.js.map