// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.controller('Edit', [
    '$scope', '$state', function($scope, $state) {
      return $scope.Edit = function(id, student) {};
    }
  ]);

}).call(this);

//# sourceMappingURL=Edit.js.map