// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.controller('Edit', [
    '$scope', '$state', '$stateParams', 'Factory', function($scope, $state, $stateParams, factory) {
      var id, student;
      id = $stateParams.id;
      student = factory.get({
        id: id
      });
      $scope.student = student;
      return $scope.Update = function(id, student) {
        return factory.update({
          id: id,
          studentToupdate: student
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=Edit.js.map