// Generated by CoffeeScript 1.7.1
(function() {
  SiteAngular.Student.controller('List', [
    '$scope', '$state', 'Factory', function($scope, $state, factory) {
      var init;
      init = function() {
        factory.query().$promise.then(function(result) {
          $scope.students = result;
        });
      };
      init();
      $scope.Delete = function(id, idx) {
        factory.remove({
          'id': id
        }).$promise.then(function(result) {
          $scope.students.splice(idx);
          toastr.success("Student Deleted.");
          init();
        }, function(error) {
          toastr.error(error.data.Message);
        });
      };
      $scope.changeStatus = function(id) {};
    }
  ]);

}).call(this);

//# sourceMappingURL=List.js.map